language: python
python:
  - "3.4"
sudo: false

# command to install dependencies
install: "pip install -r requireents/develop.txt"

# command to run tests
script: py.test && pylint ChildSoldier

# notifications
notifications:
  slack: outreach2015:rAnIvuM3klyHrwQDQJHvXbJ1